---
title: "R Tips"
author: "Kevin Putschko"
date: "August 28, 2018"
output: 
  html_document:
    keep_md: TRUE
---

### tibble::enframe()

```{r setup, include=FALSE}
library(tidyverse)
```

This is a wonderful little function to use when working with named vectors or lists, and you want to convert them to a dataframe format.  

Let's begin by defining a named vector.  In my experience, this could represent a mapping of column names from a raw text file to more meaningful names.
```{r}
vector_1 <- 
  c(column_1 = "Person", 
    column_2 = "Place",
    column_3 = "Thing")

vector_1
```

```{r}
vector_1 %>% enframe()
```


```{r}
list_1 <- 
  list(table = tibble(a = 1:5, b = 21:25),
       string = "words, words, words",
       vector = letters[1:10])

list_1
```


```{r}
list_1 %>% enframe()
```

```{r}

run_time_1 <- 20
run_time_2 <- 10

condition_3 <- runif(0, 1, n = 1) 
if (condition_3 > 0.95) {run_time_3 <- 60}

run_time_4 <- 30
run_time_5 <- 40

ls(pattern = "run_time_") %>% 
  mget(envir = .GlobalEnv) %>% 
  enframe() %>% 
  unnest()
```

